/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ruleta;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Ague
 */
public class blackjack extends javax.swing.JFrame {

    int[] resultados;
    int i, accion = 0, resultado;
    Mano manoJugador;
    boolean primera = true;
    boolean bancarrota = false;
    usuario user;
    DefaultListModel modelo = new DefaultListModel();
    Baraja baraja = new Baraja();
    boolean fin = false;

    /**
     * Creates new form blackjack
     */
    public blackjack(usuario u) {
        initComponents();
        user = u;
        fichas.setText(String.valueOf(user.getFichas()));
        nick.setText(user.getNick());
        manoJugador = new Mano();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nick = new javax.swing.JLabel();
        fichas = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cartasActuales = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        puntos = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        apostar = new javax.swing.JSpinner();
        jugar = new javax.swing.JButton();
        robar = new javax.swing.JButton();
        plantarse = new javax.swing.JButton();
        pregunta = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        mensajes = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ruleta/user-icon.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ruleta/coin-icon.png"))); // NOI18N

        nick.setText("nick");

        fichas.setText("fichas");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ruleta/iconomanocartas.png"))); // NOI18N

        jLabel6.setText("Tus cartas:");

        jScrollPane1.setViewportView(cartasActuales);

        jLabel7.setText("Suma Total:");

        puntos.setText("Puntos");

        jLabel9.setText("Apuesta:");

        jugar.setText("JUGAR");
        jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugarActionPerformed(evt);
            }
        });

        robar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ruleta/robaricon.png"))); // NOI18N
        robar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        robar.setEnabled(false);
        robar.setMaximumSize(new java.awt.Dimension(75, 75));
        robar.setMinimumSize(new java.awt.Dimension(75, 75));
        robar.setPreferredSize(new java.awt.Dimension(75, 75));
        robar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                robarActionPerformed(evt);
            }
        });

        plantarse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ruleta/plantarse.png"))); // NOI18N
        plantarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        plantarse.setEnabled(false);
        plantarse.setMaximumSize(new java.awt.Dimension(75, 75));
        plantarse.setMinimumSize(new java.awt.Dimension(75, 75));
        plantarse.setPreferredSize(new java.awt.Dimension(75, 75));
        plantarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plantarseActionPerformed(evt);
            }
        });

        jLabel4.setText("ROBAR CARTA");

        jLabel8.setText("PLANTARSE");

        mensajes.setColumns(20);
        mensajes.setRows(5);
        jScrollPane2.setViewportView(mensajes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(apostar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jugar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pregunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(robar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))
                                        .addGap(49, 49, 49)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel8))
                                            .addComponent(plantarse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 55, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fichas)
                            .addComponent(nick)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(puntos)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(nick))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(fichas)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(apostar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jugar))
                        .addGap(18, 18, 18)
                        .addComponent(pregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(puntos)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(robar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(plantarse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8))
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugarActionPerformed
        // TODO add your handling code here:
        if (Integer.parseInt(apostar.getValue().toString()) <= user.getFichas() 
                && user.getFichas() > 0 && Integer.parseInt(apostar.getValue().toString()) > 0) {


            manoJugador.setApuesta(Integer.parseInt(apostar.getValue().toString()));
            apostar.setEnabled(false);
            jugar.setEnabled(false);

            
            /**
             * Barajamos y repartimos*
             */
            baraja.barajar();

            /**
             * La banca roba sus cartas
             */
            Mano manoBanca = new Mano();
            manoBanca.cogerCarta(baraja.robar());
            manoBanca.cogerCarta(baraja.robar());

            
            /**
             * En resultado almacenamos lo que ha hecho el jugador. 0 en un
             * principio, -1 si se pasa o pierde y 1 si gana. Pondremos un 2 en
             * caso de blackjack.
             */
            int i, j;

            /**
             * El jugador roba sus cartas
             */
            manoJugador.cogerCarta(baraja.robar());
            modelo.addElement(manoJugador.obtenerCarta(0));
            manoJugador.cogerCarta(baraja.robar());
            modelo.addElement(manoJugador.obtenerCarta(1));
            cartasActuales.setModel(modelo);
            puntos.setText(String.valueOf(manoJugador.getBlackjackValor()));

            /**
             * En caso de que el usuario consiga Blackjack (21 a la primera)
             * gana el doble de la apuesta y se acaba la ronda
             */
            if ((manoJugador.getBlackjackValor() == 21)) {
                mensajes.setText(mensajes.getText() + "\n" + "La banca tiene "
                        + manoBanca.obtenerCarta(0)
                        + " y " + manoBanca.obtenerCarta(1) + ".");
                mensajes.setText(mensajes.getText() + "\n" + "El jugador " + " tiene "
                        + manoJugador.obtenerCarta(0)
                        + " y " + manoJugador.obtenerCarta(1) + ".");
                mensajes.setText(mensajes.getText() + "\n" + "El jugador " + " tiene Blackjack y gana");
                resultado = 2;
                fin = true;
            }

            /**
             * En caso de que la banca consiga Blackjack (21 a la primera) gana
             * el doble de la apuesta y se acaba la ronda
             */
            if ((manoBanca.getBlackjackValor() == 21)) {
                mensajes.setText(mensajes.getText() + "\n" + "La banca tiene "
                        + manoBanca.obtenerCarta(0)
                        + " y " + manoBanca.obtenerCarta(1) + ".");
                mensajes.setText(mensajes.getText() + "\n" + "El jugador " + " tiene "
                        + manoJugador.obtenerCarta(0)
                        + " y " + manoJugador.obtenerCarta(1) + ".");
                mensajes.setText(mensajes.getText() + "\n" + "La Banca " + " tiene Blackjack y gana");

            }

            /**
             * Mostramos una de las cartas de la banca
             */
            mensajes.setText("La Banca te muestra una carta: " + manoBanca.obtenerCarta(0));

            /**
             * Preguntamos al usuario qué quiere hacer
             */
            pregunta.setText("¿Qué quieres hacer?");

            robar.setEnabled(true);
            plantarse.setEnabled(true);


        }
    }//GEN-LAST:event_jugarActionPerformed


    private void robarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_robarActionPerformed
        //robar.setEnabled(false);
        //plantarse.setEnabled(false);
        Carta newCarta = baraja.robar();
                    manoJugador.cogerCarta(newCarta);

                    mensajes.setText(mensajes.getText() + "\n" + "Robas una carta.");
                    mensajes.setText(mensajes.getText() + "\n" + "Has robado: " + newCarta);
                    modelo.addElement(newCarta);
                    mensajes.setText(mensajes.getText() + "\n" + "Tienes "
                            + manoJugador.getBlackjackValor() + " puntos");
                    puntos.setText(String.valueOf(manoJugador.getBlackjackValor()));
                    /**
                     * 
                     */
                    if (manoJugador.getBlackjackValor() > 21) {
                        mensajes.setText(mensajes.getText() + "\n" + "El jugador " + " se ha pasado de 21. Ha perdido");
                        jugar.setEnabled(true);
                        robar.setEnabled(false);
                        plantarse.setEnabled(false);
                        modelo.clear();
                        

                    }

    }//GEN-LAST:event_robarActionPerformed

    private void plantarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plantarseActionPerformed
        // TODO add your handling code here:
        robar.setEnabled(false);
        plantarse.setEnabled(false);
        mensajes.setText(mensajes.getText() + "\n" + "El Jugador se planta");

    }//GEN-LAST:event_plantarseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner apostar;
    private javax.swing.JList<String> cartasActuales;
    private javax.swing.JLabel fichas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jugar;
    private javax.swing.JTextArea mensajes;
    private javax.swing.JLabel nick;
    private javax.swing.JButton plantarse;
    private javax.swing.JLabel pregunta;
    private javax.swing.JLabel puntos;
    private javax.swing.JButton robar;
    // End of variables declaration//GEN-END:variables
}
