/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ruleta;

import java.awt.BorderLayout;

/**
 *
 * @author Romacho
 *
 * @see ruleta.usuario
 *
 * @see ruleta.reproductor
 */
public class Menu extends javax.swing.JFrame {

    usuario user;
    Log log;
    reproductor musica;

    /**
     * Constructor de la clase
     *
     * Menu principal donde verás tu avatar, información de usuario y tendrás
     * acceso a todas las demás partes del programa
     *
     * Incluye un método interno para actualizar la info del usuario y su avatar
     * seleccionado
     *
     *
     * - user contiene el usuario
     *
     * - musica contiene el reproductor de música
     *
     * @see ruleta.panelusuer
     */
    public Menu(usuario s, Log l, reproductor m) {
        initComponents();
        user = s;
        nick.setText(user.getNick());
        fichas.setText(String.valueOf(s.getFichas()));
        log = l;
        musica = m;

        /**
         * El usuario posee una ID asociada a su avatar seleccionado, este
         * método analiza esa ID y muestra dicho avatar en la sección de usuario
         */
        switch (user.getSeleccion().getCodigo()) {
            case 1:
                avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ruleta/avatar1.jpg")));

                break;
            case 2:
                avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ruleta/avatarF2.png")));

                break;
            case 3:
                avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ruleta/avatarF1.png")));
                break;
            case 4:
                avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ruleta/avatarF3.png")));
                break;
            case 5:
                avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ruleta/avatarF4.png")));
                break;
            case 6:
                avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ruleta/avatarF5.png")));
                break;
            case 7:
                avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ruleta/avatarF6.png")));
                break;
            case 8:
                avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ruleta/avatarM1.png")));
                break;
            case 9:
                avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ruleta/avatarM2.png")));
                break;
            case 10:
                avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ruleta/avatarM3.png")));
                break;
            case 11:
                avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ruleta/avatarM4.png")));
                break;
            case 12:
                avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ruleta/avatarM5.png")));
                break;
            default:
                avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ruleta/avatar1.jpg")));

                break;
        };
        setLocationRelativeTo(null);
        fondomenu fon = new fondomenu();
        this.add(fon, BorderLayout.CENTER);
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nick = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fichas = new javax.swing.JLabel();
        botonTienda = new javax.swing.JButton();
        botonPanel = new javax.swing.JButton();
        avatar = new javax.swing.JLabel();
        botonLogout = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        botonBlackJack = new javax.swing.JButton();
        botonRuleta = new javax.swing.JButton();
        botonTragap = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Casino Romacho");
        setBackground(new java.awt.Color(0, 0, 0));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setPreferredSize(new java.awt.Dimension(882, 382));
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        nick.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nick.setForeground(new java.awt.Color(255, 255, 102));
        nick.setText("User");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 102));
        jLabel3.setText("Fichas:");

        fichas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fichas.setForeground(new java.awt.Color(255, 255, 102));
        fichas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fichas.setText("0");

        botonTienda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ruleta/botonshop.jpg"))); // NOI18N
        botonTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTiendaActionPerformed(evt);
            }
        });

        botonPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ruleta/botoncloset.jpg"))); // NOI18N
        botonPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPanelActionPerformed(evt);
            }
        });

        avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ruleta/avatar1.jpg"))); // NOI18N

        botonLogout.setText("Cambiar usuario");
        botonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLogoutActionPerformed(evt);
            }
        });

        botonBlackJack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ruleta/botonblackjack.jpg"))); // NOI18N
        botonBlackJack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBlackJackActionPerformed(evt);
            }
        });

        botonRuleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ruleta/botonruleta.jpg"))); // NOI18N
        botonRuleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRuletaActionPerformed(evt);
            }
        });

        botonTragap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ruleta/botontragaperra.jpg"))); // NOI18N
        botonTragap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTragapActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ruleta/user-icon.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ruleta/coin-icon.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(avatar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonLogout)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nick, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fichas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addComponent(botonPanel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonTienda))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonBlackJack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonRuleta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonTragap)))
                .addGap(0, 23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(avatar)
                            .addComponent(botonPanel)
                            .addComponent(botonTienda))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nick)
                            .addComponent(jLabel6))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(fichas))
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonLogout)
                        .addGap(26, 26, 26)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonBlackJack)
                    .addComponent(botonRuleta)
                    .addComponent(botonTragap))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Lanza la aplicación de la ruleta
     *
     * @see ruleta.ruleta_interfaz
     * @param evt
     */
    private void botonRuletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRuletaActionPerformed
        // TODO add your handling code here:
        ruleta_interfaz rul = new ruleta_interfaz(user, this);

        rul.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonRuletaActionPerformed

    /**
     * Lanza la aplicación de la tragaperras
     *
     * @see ruleta.tragaperras_interfaz
     * @param evt
     */
    private void botonTragapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTragapActionPerformed
        // TODO add your handling code here:
        tragaperras_interfaz trg = new tragaperras_interfaz(user, this);

        trg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonTragapActionPerformed

    /**
     * lanza la aplicación del Black Jack 21
     *
     * @see ruleta.blackjack
     * @param evt
     */
    private void botonBlackJackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBlackJackActionPerformed
        // TODO add your handling code here:
        blackjack bj = new blackjack(user, this);
        bj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonBlackJackActionPerformed

    /**
     * Lanza la aplicación de la tienda
     *
     * @see ruleta.Tienda
     * @param evt
     */
    private void botonTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTiendaActionPerformed
        // TODO add your handling code here:
        Tienda shop = new Tienda(user, this);
        shop.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonTiendaActionPerformed

    /**
     * Lanza el panel de usuario
     *
     * @see ruleta.panelusuer
     * @param evt
     */
    private void botonPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPanelActionPerformed
        // TODO add your handling code here:
        panelusuer pan = new panelusuer(user, this, musica);
        pan.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonPanelActionPerformed

    /**
     * Este método actualiza la información del usuario (fichas y avatar
     * seleccionado) cada vez que se focusea la ventana (es decir, siempre que
     * salgamos de cualquier otra aplicación del juego).
     *
     * También actualiza el archivo user.dat por si los mecanismos propios de
     * actualización de cada clase fallasen
     *
     * @param evt
     */
    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        nick.setText(user.getNick());
        fichas.setText(String.valueOf(user.getFichas()));

        switch (user.getSeleccion().getCodigo()) {
            case 1:
                avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ruleta/avatar1.jpg")));

                break;
            case 2:
                avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ruleta/avatarF2.png")));

                break;
            case 3:
                avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ruleta/avatarF1.png")));
                break;
            case 4:
                avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ruleta/avatarF3.png")));
                break;
            case 5:
                avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ruleta/avatarF4.png")));
                break;
            case 6:
                avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ruleta/avatarF5.png")));
                break;
            case 7:
                avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ruleta/avatarF6.png")));
                break;
            case 8:
                avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ruleta/avatarM1.png")));
                break;
            case 9:
                avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ruleta/avatarM2.png")));
                break;
            case 10:
                avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ruleta/avatarM3.png")));
                break;
            case 11:
                avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ruleta/avatarM4.png")));
                break;
            case 12:
                avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ruleta/avatarM5.png")));
                break;
            default:
                avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ruleta/avatar1.jpg")));

                break;
        };
    }//GEN-LAST:event_formWindowGainedFocus


    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        log.setVisible(true);
        log.toFront();
    }//GEN-LAST:event_formWindowClosed

    /**
     * vuelve a a ventana de loggin
     *
     * @param evt
     */
    private void botonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLogoutActionPerformed
        // TODO add your handling code here:
        dispose();
        log.setVisible(true);
        log.toFront();
    }//GEN-LAST:event_botonLogoutActionPerformed

    /**
     * Método para actualizar los valores del usuario
     *
     * @deprecated
     * @param s
     */
    public void actualizaUser(usuario s) {

        user = s;
        nick.setText(user.getNick());
        fichas.setText(String.valueOf(s.getFichas()));
        setLocationRelativeTo(null);
        fondomenu fon = new fondomenu();
        this.add(fon, BorderLayout.CENTER);
        this.pack();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avatar;
    private javax.swing.JButton botonBlackJack;
    private javax.swing.JButton botonLogout;
    private javax.swing.JButton botonPanel;
    private javax.swing.JButton botonRuleta;
    private javax.swing.JButton botonTienda;
    private javax.swing.JButton botonTragap;
    private javax.swing.JLabel fichas;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nick;
    // End of variables declaration//GEN-END:variables
}
